# Generated by Django 3.1.1 on 2021-02-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('post_id', models.CharField(max_length=30)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('post_id', models.CharField(max_length=30)),
                ('headline', models.CharField(max_length=500)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('category', models.CharField(default='Other', max_length=10)),
                ('img', models.ImageField(default='static/post/img.jpg', upload_to='static/post/')),
            ],
        ),
        migrations.CreateModel(
            name='Reacton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('post_id', models.CharField(max_length=30)),
                ('reaction', models.BooleanField()),
            ],
        ),
    ]
