# Generated by Django 3.1.1 on 2021-02-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_id',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
