# Generated by Django 3.1.1 on 2021-02-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comments_comment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailverify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('activation_key', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Forgetpass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('verification_key', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameModel(
            old_name='Reacton',
            new_name='Reaction',
        ),
    ]
