# Generated by Django 3.1.1 on 2021-05-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210217_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='img',
            field=models.TextField(),
        ),
    ]
